-- Santiye Takip V2 - Schema
-- Uyari: V2'de `adalar`/`bloklar` tablolari kaldirildi; yapi bilgisi
-- `santiye_config` tablosu + bundle icindeki `data/santiye.config.json`'dan gelir.
--
-- Guncel schema icin bkz. supabase/migrations/:
--   0001_v2_initial_schema.sql  (tablolar, RLS, fonksiyonlar, realtime)
--   0002_harden_function_execute.sql (yardimci fonksiyon erisimi)
--
-- Migrasyonlar MCP/Supabase CLI ile remote projeye uygulanir.
