-- Santiye Takip V2 - Seed
-- V2'de yapi bilgisi DB tablosundan degil, `santiye.config.json` + `santiye_config` tablosundan gelir.
-- Bu nedenle adalar/bloklar insert'i kaldirildi.
--
-- Veri seed islemleri (npm run ...):
--   seed:config  -> data/santiye.config.json'i `santiye_config` tablosuna yazar (service role)
--   seed:users   -> auth.users + `kullanicilar` tablosunu data/personel.json'dan olusturur
--
-- Auth trigger (`handle_new_user`) yeni auth kullanicilarini otomatik olarak
-- `kullanicilar` tablosuna tasir; seed scriptleri idempotent'tir.
